### ISSUE TITLE
Type unstable?

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaMath/QuadGK.jl#15]
I ran 
```jl
@code_warntype quadgk( x->x, 0., 1. )
```
today and it says, that the return type doesn't get inferred. Is it me or is it a bug?

**Comment by ararslan** [comment]
Which Julia version are you running this on?

**Comment by BeastyBlacksmith** [comment]
Well on 0.6.1 the return type was `Tuple{Any,Any}` and on 0.6.2 the return type is `Union{}`.
Somehow I expect it to return `Tuple{Float64,Float64}` with real valued input.

**Comment by ararslan** [comment]
Looks like Julia has never been able to infer this particular method; I checked in 0.4, 0.5, 0.6, and current 0.7. If that's the case I don't think there's much we can do here.

**Comment by BeastyBlacksmith** [comment]
Well as a workaround one could use explicit typeassertion for the return value, but I don't know if that will hurt the performance.

**Comment by kaslusimoes** [comment]
I'm a bit confused.. so there is nothing we can do?
Thanks

**Comment by ararslan** [comment]
It's certainly possible, it just requires someone tracking down the underlying issue and addressing it. :slightly_smiling_face:

**Comment by stevengj** [comment]
See JuliaLang/julia#18928

**Comment by mbesancon** [comment]
Confirming this is still the case
```julia
@code_warntype QuadGK.quadgk(x -> x*fx7(x), 0.0, 3.0)
```

```
Variables:
  #self# <optimized out>
  f::##63#64
  a::Float64
  b::Float64
  c <optimized out>

Body:
  begin 
      SSAValue(1) = (Base.Math.sqrt_llvm)(2.220446049250313e-16)::Float64
      SSAValue(0) = $(Expr(:invoke, MethodInstance for power_by_squaring(::Int64, ::Int64), :(Base.power_by_squaring), 10, 7))
      return $(Expr(:invoke, MethodInstance for do_quadgk(::##63#64, ::Array{Float64,1}, ::Int64, ::Type{Float64}, ::Float64, ::Float64, ::Int64, ::Base.LinAlg.#vecnorm), :(QuadGK.do_quadgk), :(f), :($(Expr(:invoke, MethodInstance for vect(::Float64, ::Vararg{Float64,N} where N), :(Base.vect), :(a), :(b)))), 7, Float64, :((Base.sitofp)(Float64, 0)::Float64), SSAValue(1), SSAValue(0), :(QuadGK.vecnorm)))
  end::Tuple{Any,Any}
```

**Comment by matbesancon** [comment]
#21 got irrelevant for most parts, and some parts are contested. 
One work-around I would propose: dispatch on a special case when we are in one dimension and make this one type-stable, let the rest as-is.
