### ISSUE TITLE
Segmentation fault when integrating a unitful function

### ISSUE THREAD

**Issue by MasonProtter** [JuliaMath/QuadGK.jl#17]
Two  minimal working examples:
```julia
using QuadGK, Unitful
f(x) = x^2u"m"
quadgk(f, 0, 1)
```
and
```julia
using QuadGK, Unitful
f(x) = x^2
quadgk(f, 0u"m", 1u"m")
```
both crash Julia for me. 

Seems to be directly related to #13. In hindsight, this probably could have been a comment in that thread. Should I remove this issue and move its contents there?

**Comment by stevengj** [comment]
No need to move the contents, but yes, closing as a duplicate.
