### ISSUE TITLE
rulekey internal function undocumented and type unstable 

### ISSUE THREAD

**Issue by matbesancon** [JuliaMath/QuadGK.jl#20]
```julia
rulekey(::Type{BigFloat}, n) = (BigFloat, precision(BigFloat), n)
rulekey(T,n) = (T,n)
```

The function returns either a triplet or a pair, this would make it easier to reason about if it returned always the same structure and types

**Comment by mbesancon** [comment]
This propagates to `const rulecache = AnyDict...`
The Dict has to be of type {Any,Any} because of the key type variation

**Comment by stevengj** [comment]
Yes, it wouldn't hurt to always return the triplet.
