### ISSUE TITLE
incorrect error message

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaMath/QuadGK.jl#22]
A simple syntax error when calling QuadGK returns an error giving the impression that QuadGK is not installed:
```julia
julia> using QuadGK

julia> g(x)=x^2
g (generic function with 1 method)

julia> quadgk(f,(0,1))
ERROR: quadgk(f, (0, 1)) has been moved to the package QuadGK.jl.
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `using QuadGK`.
Stacktrace:
 [1] #quadgk#771(::Array{Any,1}, ::Function, ::Function, ::Vararg{Any,N} where N) at ./deprecated.jl:698
 [2] quadgk(::Function, ::Tuple{Int64,Int64}) at ./deprecated.jl:698

julia> 
```

This can cause quite a bit confusion for students learning Julia (and even some of the more familiar!). 

By the way, great package!

**Comment by stevengj** [comment]
This is a general problem with these deprecations, it should be a MethodError.  This will go away in 0.7, but it's not practical to do much about it now.
