### ISSUE TITLE
Incorrect error estimate depending on a very specific value of a parameter

### ISSUE THREAD

**Issue by ikirill** [JuliaMath/QuadGK.jl#26]
I think there's something wrong with the way quadgk handles this integral, the error estimate is almost zero but the answer is substantially inaccurate. Just replacing 0.499 with 0.4999 fixes it:

```
julia> check(f,a,b) = let (x1,e1) = QuadGK.quadgk(f,a,b); (x2,e2) = QuadGK.quadgk(f,big(a),big(b)); (Float64(abs(x1-x2)), e1); end
check (generic function with 1 method)

julia> check(x -> exp(abs(x-0.499)), 0, 1)
(1.0000000833402914e-6, 2.220446049250313e-16)

julia> check(x -> exp(abs(x-0.4999)), 0, 1)
(7.284892445276705e-17, 1.1102230246251565e-16)
```

It's an easy integral, so zero error estimate can be expected, but there could be something going wrong with the integral value it actually returns.

**Comment by stevengj** [comment]
It's not at all an "easy" integral, because the integrand has a slope discontinuity in the middle of the integration region.   QuadGK, like essentially all integration algorithms, is best for smooth integrands.  The discontinuity not only messes up the convergence rate, it also messes up the error estimate.

**Comment by stevengj** [comment]
An accurate way to do this integral is to break the integration interval up into the regions before and after the discontinuity:
```jl
julia> x1,e1 = QuadGK.quadgk(x -> exp(abs(x - 0.499)), 0, 1) # inaccurate
(1.297443190121581, 2.220446049250313e-16)

julia> x2,e2 = QuadGK.quadgk(x -> exp(abs(x - 0.499)), 0, 0.499, 1) # accurate
(1.2974441901216642, 1.1102230246251565e-16)

julia> x1-x2 # error
-1.0000000831844602e-6
```
The same procedure shows the error with 0.4999 is *not* 1e-17:
```jl
julia> x1,e1 = QuadGK.quadgk(x -> exp(abs(x - 0.4999)), 0, 1)
(1.297442547887469, 1.1102230246251565e-16)

julia> x2,e2 = QuadGK.quadgk(x -> exp(abs(x - 0.4999)), 0, 0.4999, 1)
(1.2974425578874689, 1.1102230246251565e-16)

julia> x1-x2
-9.99999993922529e-9
```

**Comment by ikirill** [comment]
Yikes, I see, I messed that up, I thought the BigFloat version was okay.

**Comment by ikirill** [comment]
Would you consider the incorrect error estimate a bug on its own? (I was reading https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/13300/eth-65-02.pdf and just wanted to see what QuadGK would do on some of the test functions.)

**Comment by stevengj** [comment]
I wouldn't consider that a bug, I would consider that an inherent limitation of Gauss–Kronrod adaptive quadrature.
