### ISSUE TITLE
Numerical integration with variable boundaries

### ISSUE THREAD

**Issue by jicky94** [JuliaMath/QuadGK.jl#27]
Hi,

Is there another way than using Sympy from Python?

If i do need to use it, as my integral is within a function and part of a larger numerical problem, should i then reconvert all my variables into Julia types (I mean versus symbolic - type Sym- that I had to convert them into to use integrate)? 

Many thanks.

**Comment by jicky94** [comment]
Should I rather in this case use Riemann sums as an approximation?

**Comment by stevengj** [comment]
Could you be more precise about what you are trying to do?

**Comment by jicky94** [comment]
Thanks. So I have a system of equation. One of them include an integral whose boundary is one of the unknowns. And I am not able to find how to implement a boundary variable integration. My question is close to that one in a sense https://github.com/JuliaMath/QuadGK.jl/issues/13 : i need to integrate over other types than real and complex numbers - i think.

I tried using the Python Sympy but 1.) I get a method error and 2.) I am unclear on how to switch to symbolic mathematics to then switch back to numerical and unsure if that would make any sense (never coded on matlab or similar, so forgive my ignorance).

Therefore -thinking the solution above is not suited- I thought of trying out a (probably bad?) approximation of the integral through Riemann sums.

What do you think? Let me know if i was unclear. Thanks a lot!!

**Comment by stevengj** [comment]
I still don't understand — are you trying to do the integral symbolically?  In that case, you can't use this package.

If you are solving the system of equations *numerically* (e.g. by Newton's method), and an equation involves an integral, then you can use this package to compute the integral numerically with no problems.

You could also look at https://github.com/JuliaApproximation/ApproxFun.jl for a numerical approach that has some flavor of the symbolic approach.
