### ISSUE TITLE
quadgk holds DataStructures.jl to v0.15

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaMath/QuadGK.jl#39]
QuadGK is holding my DataStructures to v0.15. 

What is the reason for these lines in the Project.toml?
```
[compat]
DataStructures = "0.11, 0.12, 0.13, 0.14, 0.15"
```

**Comment by neversakura** [comment]
It seems to be OK to add 0.17 to `compat`.

**Comment by CarloLucibello** [comment]
I would just go with
```
[compat]
DataStructures = " >= 0.11"
```
to avoid similar problems in the feature. In any case, wether we go with the lower bound or the explicit version list, could you tag a new release?
