### ISSUE TITLE
Add support for DataStructures 0.18

### ISSUE THREAD

**Issue by atrophiedbrain** [JuliaMath/QuadGK.jl#47]
DataStructures 0.18 is out, can this package be revised to support it? I am having conflicts between this package and the latest version of DiffEqBase due to this dependency version.

**Comment by stevengj** [comment]
Yes, 0.18 should be fine; I will update the Project.toml

(I wish DataStructures would just tag 1.0.)

**Comment by stevengj** [comment]
closed by 01d24d87a8d6a115279678fc041b0de83e5b7bf1
