### ISSUE TITLE
Quadrature points and weights in the intervals [0, Inf] and [-Inf, +Inf]

### ISSUE THREAD

**Issue by nhavt** [JuliaMath/QuadGK.jl#53]
Hi there, I would like to ask a question regarding quadrature points and weights in the intervals` [0, +Inf]` and `[-Inf, +Inf]`. At the moment, it seems that I could not get quadrature points and weights in these intervals using the command `gauss(N,a,b)`. However, it is possible to find `quadgk(x -> exp(-x^2), -Inf, +Inf)` or `quadgk(x -> exp(-x^2), 0, +Inf)`. So, my question here is that will the command `gauss(N,a,b)` support the intervals `[0, Inf]` and `[-Inf, +Inf]` in a near future?  Or I have to perform a change of variable to scale these intervals into finite intervals to get the quadrature points and weights?

**Comment by frankier** [comment]
Yes you do have to do a transformation. This is what `handle_infinities` does internally: https://github.com/JuliaMath/QuadGK.jl/blob/298f76e71be8a36d6e3f16715f601c3d22c2241c/src/adapt.jl#L89

**Comment by stevengj** [comment]
Alternatively, if you know the asymptotic decay rate of your function (e.g. if you know it decays exponentially), you can use a specialized quadrature rule like Gauss–Laguerre quadrature (from https://github.com/JuliaApproximation/FastGaussQuadrature.jl).
