### ISSUE TITLE
documentation build is failing

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/QuadGK.jl#70]
Some problem with the `DOCUMENTER_KEY` ssh key according to the logs.
```
Initialized empty Git repository in /tmp/jl_B4CaCu/.git/
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:JuliaMath/QuadGK.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/6vUwN/src/Documenter.jl:552
```

**Comment by stevengj** [comment]
We have a `DOCUMENTER_KEY` "secret" for this repo but it appears to be blank?
<img width="957" alt="image" src="https://user-images.githubusercontent.com/2913679/217396131-5d90c66f-e3fe-4e37-b0d5-6acc7b2e36ad.png">

**Comment by stevengj** [comment]
Okay, I just ran `DocumenterTools.genkeys(QuadGK)` and added a `documenter` public key with read/write access to https://github.com/JuliaMath/QuadGK.jl/settings/keys and added the corresponding `DOCUMENTER_KEY` in https://github.com/JuliaMath/QuadGK.jl/settings/secrets
…
hopefully this will work if I now push a commit?

**Comment by stevengj** [comment]
Success! But the link has now changed to https://juliamath.github.io/QuadGK.jl/dev/

**Comment by DonggeJia** [comment]
DocumenterTools.genkeys(QuadGK) does not work for me, I geenrate dozens of keys, no pair of them works. Always erros:
Error: Git failed to fetch git@github.com:DonggeJia/try1.jl
This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
Make sure that the environment variable is properly set up as a Base64-encoded string
of the SSH private key. You may need to re-generate the keys with DocumenterTools.

**Comment by RainerHeintzmann** [comment]
I had a similar problem and GitHub kept rejecting the keys generated by `DocumenterTools.genkeys()`, saving to `mykey`. I ended up using Windows Powershell and `ssh-keygen` and converting them in Julia to Base64 like this
```julia
using Base64
read(raw"mykey", String) |> base64encode |>  println
read(raw"mykey.pub", String) |>  println
```
and pasting these output into GitHub.

**Comment by giordano** [comment]
I don't see how the last comments are relevant to this issue (which had been resolved almost three years ago). If you have problems with the deployment of docs for your own package you should discuss this on the Documenter.jl repository. I'm going lock this issue to stop further unrelated discussions.
