### ISSUE TITLE
Misleading deprecation advice

### ISSUE THREAD

**Issue by jarvist** [JuliaMath/QuadGK.jl#8]
When you follow the deprecation advice for using this package on Julia 0.6 and beyond,

```
julia> quadgk()
ERROR: quadgk() has been moved to the package QuadGK.jl.
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `using QuadGK`.
```

It does not actually work due to a clash with the deprecation warning itself.

```
julia> using QuadGK
julia> quadgk()
WARNING: both QuadGK and Base export "quadgk"; uses of it in module Main must be qualified
ERROR: UndefVarError: quadgk not defined
```

I believe the above was working on MASTER sometime over Winter 2016 / Spring 2017, as I had added `using QuadGK` to all my codes to make the deprecation warning go away!

Instead you must import the function(s) you want explicitly,
```
julia> import QuadGK.quadgk
julia> quadgk
quadgk (generic function with 3 methods)
```

Or reference the QuadGK package every time you call the function,
```
julia> using QuadGK
julia> QuadGK.quadgk
quadgk (generic function with 3 methods)
```

See also discussion at: 
https://github.com/JuliaLang/julia/pull/19741

Can the QuadGK functions be forcibly exported into the namespace when the packaged is `using`'d ? That would seem to be the expected behaviour by the user.

**Comment by stevengj** [comment]
No.  I don't think this is something that can be fixed in QuadGK.jl

**Comment by ararslan** [comment]
I think it can with some choice `import`ing, as was done with Primes.
